package:
  format-version: "1.0.0"
  name: "replaceme"
  type: "application"
  status: "beta"
  required: false
  version: "v1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.22.0"
